apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sonatypenxrms.apigw.sonatypenxrm.com
spec:
  group: apigw.sonatypenxrm.com
  names:
    kind: SonatypeNXRM
    listKind: SonatypeNXRMList
    plural: sonatypenxrms
    singular: sonatypenxrm
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
