apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nxrms.apm.nxrm.com
spec:
  group: apm.nxrm.com
  names:
    kind: NXRM
    listKind: NXRMList
    plural: nxrms
    singular: nxrm
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
